---
title: "Chicago Expense Analysis"
author: "Michael Molloy"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: tango
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    includes:
          after_body: "./assets/html/footer.html"
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE}
library(tidyverse)
library(magrittr)
library(lubridate)
```

# Chicago Expense Analysis

```{r}

#read data
Expenses <- read_rds("./input/source/expense/Expenses.Rds")
```

## Total Budget

```{r}
# calculate the total budget by year

Expenses%>% 
  mutate(Month = month(Date),
         Year = year(Date)) %>% 
  filter(Year == 2018) %>% 
  group_by(Year,Month) %>% 
  summarize(Count = n(), Amount = sum(Amount)) %>% 
ggplot(aes(Month, Amount, size = Count)) +
  geom_point() +
  scale_size_continuous(labels = scales::comma, breaks = c(300,400,500,600)) +
  scale_x_continuous(breaks = 1:12) +
  labs(title = "City of Chicago Employee Expenses", subtitle = "Year 2018", x = "Month", y = "Total $", size = "# of transactions")
```

## Top Departments
By addind up the budgets for all of the years in our dataset, by department, we can see which departments have had the largest vendor payments

```{r}
# total budget by department
TopDepartments <- Expenses %>%
  filter(Department != "NA") %>% 
  group_by(Department = Department) %>% 
  summarize(Amount = sum(Amount)) %>%
  arrange(desc(Amount)) %>%
  head(12) %>% 
  mutate(Amount = Amount/10000000)

TopDepartments %>% 
  ggplot(aes(reorder(Department,Amount),Amount, fill = as.factor(Amount))) +
  geom_col() +
  guides(fill=FALSE)+
  coord_flip() + 
  labs(title = "Top Employee Expenses", subtitle = "by Department", x= "",y = "$ (in Millions)")
```

Then we can dive deeper into the top 10 departments to see how their budgets have changed over time.

```{r}
Expenses %>% 
  filter(Expenses$Department %in% TopDepartments$Department) %>% 
  filter(Department != "NA") %>% 
  filter(year(Date) == 2018) %>% 
  group_by(Department, Month = month(Date)) %>% 

summarise(Amount = sum(Amount)) %>% 
  mutate(Amount = Amount/1000) %>% 
    ggplot(aes(Month,Amount,fill = Department)) +
    geom_col(show.legend = F) +
  scale_x_continuous(breaks = c(3,6,9,12)) +
  facet_wrap(~Department, scales = "free") +
    labs(title = "Employee Expenses", subtitle = "by Department",caption = "City of Chicago, 2018", x= "",y="$(in thousands)")
  
```

## Top Paid Vendors

```{r}
# total budget by department
Expenses %>%
  filter(year(Date) == 2018) %>% 
group_by(Vendor) %>% 
  summarize(Count = n(), Amount = round(sum(Amount)), Average = round(Amount/Count)) %>% 
  arrange(-Amount) %>% 
  head(20)

```

# Expense Types

```{r}
Expenses %>% 
  group_by(Description) %>% 
  summarize(Count = n()) %>% 
  arrange(-Count)


 Expenses[str_detect(Expenses$Description,"TUITION"),] %>% 
     group_by(Department, Month = month(Date)) %>% 

summarise(Amount = sum(Amount)) %>% 
  mutate(Amount = Amount/1000) %>% 
    ggplot(aes(Month,Amount,fill = Department)) +
    geom_col(show.legend = F) +
  scale_x_continuous(breaks = c(3,6,9,12)) +
  facet_wrap(~Department, scales = "free") +
    labs(title = "Employee Expenses", subtitle = "by Department",caption = "City of Chicago, 2018", x= "",y="$(in thousands)")
   
```


